export const selectorIdP = document.querySelector('#select-idp')
export const buttonLogin = document.querySelector('#btnLogin')
buttonLogin.setAttribute('disabled', 'disabled')
export const buttonRead = document.querySelector('#btnRead')
buttonRead.setAttribute('disabled', 'disabled')
export const selectorPod = document.querySelector('#select-pod')
export const labelCreateStatus = document.querySelector('#labelCreateStatus')
export const buttonCreate = document.querySelector('#btnCreate')
buttonCreate.setAttribute('disabled', 'disabled')